<color=green>Anglerfish:</color> "You sure are lost, aren’t you land dweller?"
You: "My submarine exploded, could you take me back to the surface?"
<color=green>Anglerfish:</color> "Well, I suppose I could help you, though you'll need approval from our queen first."
You: "How do I get her approval?"
<color=green>Anglerfish:</color> "Through combat, of course! Follow me!"