You: "..."
Computer: "Reporting Internal Statistics:"
Computer: "Outside Temperature: 4 Degrees Celsius"
Computer: "Time Until Surface Reached: 4 hours"
You: "What a success! This mission couldn't have gone any better."
You: "I found the panacea, the ultimate cure to all diseases! Maybe those clowns at Conch Labs will finally give me a promotion..."
You: "Well, I should probably activate the automated return sequence and get out of here."