Queen Anglerfish: "WITNESS ME, MY MINIONS!!"
Queen Anglerfish: "It is I, the great QUEEN ANGLERFISH!"
Queen Anglerfish: "Look upon me and weep, for I -"
Queen Anglerfish: "Wait, you aren't a fish. What the heck?!"
Queen Anglerfish: "I'm not sure who let you in, but no land-dweller shall be permitted to live in my house!"
Queen Anglerfish: "Prepare to face the wrath of the sea!"